GET http://localhost:8000/api/clientes

###
GET http://localhost:8000/api/clientes/1

###

POST http://localhost:8000/api/clientes
Content-Type: application/json

{
  "nome": "Maria Matos",
  "email": "maria@gmail.com",
  "telefone":"124567994"
}

###
PUT http://localhost:8000/api/clientes/4
Content-Type: application/json

{
  "nome": "Maria Silva",
  "email": "maria@gmail.com",
  "telefone":"124567994"
}

###
DELETE  http://localhost:8000/api/clientes/5